### ISSUE TITLE
[Add Hardware]

### ISSUE THREAD

**Issue by Willian7004** [LiarOnce-LoongAL/loong-compatible-database#1]
**在提交硬件信息之前，请先阅读参与贡献的事项：https://loongarch.liaronce.com/contribution/#hardwares**

**硬件信息**
```yaml
model: s80
brand: 摩尔线程
type: GPU
status: 兼容
notes: 仅支持loongnix原生桌面环境
link: 
```

**证实硬件运行状态的信息**
![Screenshot_2024-12-31-18-03-06-84](https://github.com/user-attachments/assets/9a1ae882-4c26-46ad-9b12-daefea67e538)
![mmexport1735639610151](https://github.com/user-attachments/assets/5646f581-501b-4734-b29a-757d86b54e5c)
图源摩卡玩家小程序，本人只做数据收集。有疑问可以考虑联系图中文章作者。

**更多信息**
如果该硬件需要以文档的方式进行说明，请从这里开始
